// This mock DB is used for local bypass when DATABASE_URL is missing
export const mockNiches = [
  // --- Core Intelligence ---
  {
    id: "deep-research",
    nicheName: "Deep Research",
    icon: "Zap",
    providerModelId: "google/gemini-pro-1.5",
    systemPrompt: "Deep search and internet research mode.",
    baseCostPer1k: "0.015",
    profitMarginPercent: 40,
    isActive: true,
  },
  {
    id: "agent-swarm",
    nicheName: "Agent Swarm",
    icon: "Cpu",
    providerModelId: "meta-llama/llama-3-70b",
    systemPrompt: "Multi-agent coordination mode.",
    baseCostPer1k: "0.002",
    profitMarginPercent: 50,
    isActive: true,
  },

  // --- Technical & Web ---
  {
    id: "code-generator",
    nicheName: "Expert Developer",
    icon: "Terminal",
    providerModelId: "deepseek/deepseek-coder",
    systemPrompt: "Expert software engineer mode.",
    baseCostPer1k: "0.005",
    profitMarginPercent: 100,
    isActive: true,
  },
  {
    id: "website-builder",
    nicheName: "Website Builder",
    icon: "Layout",
    providerModelId: "moonshotai/moonshot-v1-auto",
    systemPrompt: "OLLI-E Website Builder prompt here...",
    baseCostPer1k: "0.012",
    profitMarginPercent: 50,
    isActive: true,
  },
  {
    id: "data-analyst",
    nicheName: "Data Analyst",
    icon: "BarChart",
    providerModelId: "openai/gpt-4o",
    systemPrompt: "OLLI-E Data Helper: Analyzing structured data and CSVs.",
    baseCostPer1k: "0.010",
    profitMarginPercent: 100,
    isActive: true,
  },
  {
    id: "seo-optimizer",
    nicheName: "SEO Optimizer",
    icon: "Search",
    providerModelId: "meta-llama/llama-3-8b",
    systemPrompt: "OLLI-E SEO: Keywords, meta tags, and content optimization.",
    baseCostPer1k: "0.0001",
    profitMarginPercent: 1000,
    isActive: true,
  },

  // --- Creative & Content ---
  {
    id: "content-writer",
    nicheName: "Content Writer",
    icon: "PenTool",
    providerModelId: "anthropic/claude-3.5-sonnet",
    systemPrompt: "OLLI-E Content Writer prompt here...",
    baseCostPer1k: "0.003",
    profitMarginPercent: 60,
    isActive: true,
  },
  {
    id: "image-crafter",
    nicheName: "Image Crafter",
    icon: "Palette",
    providerModelId: "openai/dall-e-3",
    systemPrompt: "Creative image generation agent.",
    baseCostPer1k: "0.040",
    profitMarginPercent: 200,
    isActive: true,
  },
  {
    id: "storyteller",
    nicheName: "Creative Storyteller",
    icon: "Sparkles",
    providerModelId: "openai/gpt-4o",
    systemPrompt: "OLLI-E Creative: Scripts, Roleplay, and Short Stories.",
    baseCostPer1k: "0.010",
    profitMarginPercent: 50,
    isActive: true,
  },
  {
    id: "youtube-scripts",
    nicheName: "YouTube Scriptwriter",
    icon: "Youtube",
    providerModelId: "google/gemini-1.5-flash",
    systemPrompt: "OLLI-E Video Helper: Viral hooks and video scripts.",
    baseCostPer1k: "0.001",
    profitMarginPercent: 200,
    isActive: true,
  },

  // --- Business & Pro Hub ---
  {
    id: "product-manager",
    nicheName: "Product Manager",
    icon: "Layers",
    providerModelId: "anthropic/claude-3.5-sonnet",
    systemPrompt: "OLLI-E PM: PRDs, User Stories, and Roadmap planning.",
    baseCostPer1k: "0.003",
    profitMarginPercent: 100,
    isActive: true,
  },
  {
    id: "social-media",
    nicheName: "Social Media Manager",
    icon: "Share2",
    providerModelId: "meta-llama/llama-3-70b",
    systemPrompt: "OLLI-E Social Media: Posts for Insta, Twitter, and LinkedIn.",
    baseCostPer1k: "0.001",
    profitMarginPercent: 300,
    isActive: true,
  },
  {
    id: "email-architect",
    nicheName: "Email Architect",
    icon: "Mail",
    providerModelId: "anthropic/claude-3-opus",
    systemPrompt: "OLLI-E Outreach: Designing high-converting cold email sequences.",
    baseCostPer1k: "0.015",
    profitMarginPercent: 80,
    isActive: true,
  },
  {
    id: "resume-pro",
    nicheName: "Resume Pro",
    icon: "UserCircle",
    providerModelId: "anthropic/claude-3-haiku",
    systemPrompt: "OLLI-E Career Helper: Resume and Cover Letter writing.",
    baseCostPer1k: "0.0005",
    profitMarginPercent: 500,
    isActive: true,
  },
  {
    id: "legal-companion",
    nicheName: "Legal Companion",
    icon: "Scale",
    providerModelId: "openai/gpt-4o",
    systemPrompt: "OLLI-E Legal Helper: Summarizing agreements and contracts.",
    baseCostPer1k: "0.010",
    profitMarginPercent: 50,
    isActive: true,
  },
  {
    id: "language-tutor",
    nicheName: "Language Tutor",
    icon: "Languages",
    providerModelId: "google/gemini-1.5-pro",
    systemPrompt: "OLLI-E Tutor: Personalized language learning and translation.",
    baseCostPer1k: "0.007",
    profitMarginPercent: 50,
    isActive: true,
  },
];

export const mockWallet = {
  balance: "99.2500",
};

export const mockUser = {
  id: "mock_uuid_12345",
  clerkId: "user_2p5X7z9W1V3U4t5S",
  email: "local@olli-e.ai",
  isS3Configured: false,
};
