export default function PrivacyPolicyPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16 text-zinc-200 space-y-8">
      <div className="space-y-2">
        <p className="text-xs uppercase text-zinc-500 tracking-widest">Legal</p>
        <h1 className="text-4xl font-bold text-white">Privacy Policy</h1>
        <p className="text-zinc-400 text-sm">Last updated: March 20, 2026</p>
      </div>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">1. Data We Collect</h2>
        <p className="text-zinc-400 leading-relaxed">
          We collect only what is necessary to operate the Service: your email address, billing and payment records, wallet balance, and API usage metrics (token counts, timestamps). We do not collect or retain the content of your AI conversations on our servers beyond the duration of the session.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">2. Your Storage & Files</h2>
        <p className="text-zinc-400 leading-relaxed">
          All files generated by OLLI-E AI and saved by you are transmitted directly to your own Amazon S3 bucket using industry-standard, time-limited pre-signed URLs. Your files <strong>never transit through OLLI-E servers</strong>. We do not access, index, or process the contents of your S3 storage.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">3. How We Use Your Data</h2>
        <p className="text-zinc-400 leading-relaxed">
          Data is used exclusively to: provide and maintain the Service, manage your account and wallet, generate GST-compliant invoices, and calculate API usage costs. We do not sell your personal data to third parties.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">4. Third-Party Services</h2>
        <p className="text-zinc-400 leading-relaxed">
          We integrate with third-party providers to operate the Service, including authentication providers (Clerk), payment processors (Razorpay, Instamojo, Zwitch, PayPal), cloud database providers (Neon), and AI API aggregators. Each provider operates its own privacy policy.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">5. Security</h2>
        <p className="text-zinc-400 leading-relaxed">
          We implement row-level security on all database records, ensuring strict data isolation between users. API rate limiting protects your account and credit wallet from unauthorized usage. Your AWS S3 credentials are encrypted at rest using industry-standard AES-256 encryption.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">6. Data Deletion</h2>
        <p className="text-zinc-400 leading-relaxed">
          You may request deletion of your account and all associated platform data at any time by contacting support. Note that data stored in your own S3 bucket is outside our control and must be managed directly through your AWS account.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">7. Contact</h2>
        <p className="text-zinc-400 leading-relaxed">
          For privacy inquiries, contact us at: <a href="mailto:privacy@ollie-ai.com" className="text-violet-400 hover:underline">privacy@ollie-ai.com</a>
        </p>
      </section>
    </div>
  );
}
